postgresql:
  ssl_mode: disable
  allow_insecure: true

logging:
  enabled: false
  level: WARNING

failures:
  enabled: false

server_output:
  stdout: true
  file: null
  max_message_bytes: 8192
  max_messages: 1000
